### ISSUE TITLE
Unable to install frontend packages

### ISSUE THREAD

**Issue by Uhoo0125** [carefree0910/carefree-drawboard#5]
Hello! 

I successfully installed _**carefree-drawboard=0.0.2a0**_ by `pip install -e .`.

But when I run `cfdraw run` in the `examples/carefree_creator`, the following error occurs, and those urls are invalid.

![image](https://github.com/carefree0910/carefree-drawboard/assets/30224644/34156222-f3f9-439d-abf8-7c5d6cd2c03a)
![image](https://github.com/carefree0910/carefree-drawboard/assets/30224644/be73637c-7016-4b38-a502-630c2327f400)

**Comment by carefree0910** [comment]
Hello!

This looks very weird, seems to be a bug thrown by `esbuild`... Would you please pull the latest codes and see if the error still occurs?

If it does, then please provide me the error logs in texts so i can google them to see if it is due to platform / `esbuild`. 🤣

> p.s. i re-created a brand new env and successfully run through the example with the latest codes on my macbook pro m1 chip, so the codes should (probably) be ok.

**Comment by Uhoo0125** [comment]
Thank you for your prompt reply!

Yes, it's very weird.I have already pull the latest version, error still exists.

And sorry for the inconvenience caused by the screenshot. :laughing:

```
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Running app ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Installing frontend packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
warning "@carefree0910/pack_react > @chakra-ui/icons@2.0.19" has unmet peer dependency "@chakra-ui/system@>=2.0.0".                                                                                                                                                       
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/form-control@^2.0.0".                                                                                                                                                
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/icon@^3.0.0".                                                                                                                                                        
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/layout@^2.0.0".                                                                                                                                                      
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/media-query@^3.0.0".                                                                                                                                                 
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/menu@^2.0.0".                                                                                                                                                        
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/spinner@^2.0.0".                                                                                                                                                     
warning "@carefree0910/pack_react > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/system@^2.0.0".                                                                                                                                                      
warning "@carefree0910/pack_react > @chakra-ui/icons > @chakra-ui/icon@3.0.16" has unmet peer dependency "@chakra-ui/system@>=2.0.0".                                                                                                                                     
error /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild: Command failed.                                                                                                                                                                            
Exit code: 1
Command: node install.js
Arguments: 
Directory: /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild
Output:
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: /usr/bin/node /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild/bin/esbuild --version
node:child_process:926
    throw err;
    ^

<ref *1> Error: spawnSync /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/@esbuild/linux-x64/bin/esbuild EACCES
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:873:24)
    at Object.execFileSync (node:child_process:916:15)
    at Object.<anonymous> (/mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild/bin/esbuild:220:28)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawnSync /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/@esbuild/linux-x64/bin/esbuild',
  path: '/mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/@esbuild/linux-x64/bin/esbuild',
  spawnargs: [ '--version' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

Node.js v20.5.1

    at checkExecSyncError (node:child_process:887:11)
    at Object.execFileSync (node:child_process:923:15)
    at validateBinaryVersion (/mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild/install.js:98:28)
    at /mnt/Data/CodeML/SD/carefree-drawboard/cfdraw/.web/node_modules/esbuild/install.js:283:5 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(1276) [Uint8Array] [
      110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
      114, 111,  99, 101, 115, 115,  58,  57,  50,  54,  10,  32,
       32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
       59,  10,  32,  32,  32,  32,  94,  10,  10,  60, 114, 101,
      102,  32,  42,  49,  62,  32,  69, 114, 114, 111, 114,  58,
       32, 115, 112,  97, 119, 110,  83, 121, 110,  99,  32,  47,
      109, 110, 116,  47,  68,  97, 116,  97,  47,  67, 111, 100,
      101,  77,  76,  47,  83,  68,  47,  99,  97, 114, 101, 102,
      114, 101, 101,  45,
      ... 1176 more items
    ]
  ],
  pid: 7983,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(1276) [Uint8Array] [
    110, 111, 100, 101,  58,  99, 104, 105, 108, 100,  95, 112,
    114, 111,  99, 101, 115, 115,  58,  57,  50,  54,  10,  32,
     32,  32,  32, 116, 104, 114, 111, 119,  32, 101, 114, 114,
     59,  10,  32,  32,  32,  32,  94,  10,  10,  60, 114, 101,
    102,  32,  42,  49,  62,  32,  69, 114, 114, 111, 114,  58,
     32, 115, 112,  97, 119, 110,  83, 121, 110,  99,  32,  47,
    109, 110, 116,  47,  68,  97, 116,  97,  47,  67, 111, 100,
    101,  77,  76,  47,  83,  68,  47,  99,  97, 114, 101, 102,
    114, 101, 101,  45,
    ... 1176 more items
  ]
}

Node.js v20.5.1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Launching App ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  [ info ] 👌 Your app will be ready at http://localhost:5123 soon...
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Launching Backend ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  [ info ] 🚀 Starting Backend Server at http://localhost:8321 ...
>  [ info ] 🔨 Compiling Plugins & Endpoints...
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  [ info ] 📣 Notifications:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── [ GLOBAL ] ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

* This demo requires 16GB GPU memory.
* This demo migrates `carefree-creator`'s functionalities to `carefree-drawboard` 🎨:
1. Text to Image generation.
2. Image to Image generation.
3. Variation generation.
4. Super Resolution.
5. Image Matting.
6. Image Captioning.
7. Inpainting (Erase).
8. Stable Diffusion Inpainting (Erase & Replace).
9. Stable Diffusion Outpainting.
10. Image Harmonization.
11. ControlNet Hints.
12. Multi ControlNet.
13. And much more to come!

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>  [ info ] 🔔 Your files will be saved to '/mnt/Data/CodeML/SD/carefree-drawboard/examples/carefree_creator'
>  [ info ] 🎉 Backend Server is Ready!
```

**Desktop:**
 - OS: Ubuntu 20.04.3 LTS
 - CPU: AMD 5600g
 - GPU: Nvidia 4080
 - python: 3.9.0 (Anaconda)
 - nodejs: 20.5.1

> Notably, when I installed the regular version by `pip install carefree-drawboard` in a new env, `cfdraw install` ran successfully without error. However, this version does not support some of the syntax in the example. :crying_cat_face:

**Comment by carefree0910** [comment]
I see, I'll google around to see if I can find some clues, and I'll comment here if I find any! 😉

> The regular version is pretty out-of-dated (0.0.2a0, which was published in June), so it indeed lacks many syntax / features, but the fact that it can be installed is another weird stuff... Anyway, hope google can help! 🙏

**Comment by carefree0910** [comment]
@yuhaoo00 According to [this](https://github.com/evanw/esbuild/issues/369) & [this](https://stackoverflow.com/questions/75239018/npm-install-eaccess-when-try-to-install-outside-of-home-dir-on-linux), it seems to be a permission issue. Would you please try the solutions mentioned there and see if they help, thanks!

**Comment by Uhoo0125** [comment]
Yeah, this is a permission issue.

When I put the code repository under the home dir instead of the mount dir, everything is ok. (:upside_down_face: What an annoying `/mnt`!)

Thanks for your help and this very interesting project! :+1::+1::+1:
